//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGL_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliancesType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppliancesType()
        {
            this.Dehumidifiers = new HashSet<Dehumidifier>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dehumidifier> Dehumidifiers { get; set; }
    }
}
