//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EGL_V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dehumidifier
    {
        public int DehumidifiersId { get; set; }
        public string Partner { get; set; }
        public string BrandName { get; set; }
        public string ModelName { get; set; }
        public string ModelNumber { get; set; }
        public string AdditionalModelInfo { get; set; }
        public string DehumidifierType { get; set; }
        public string AlternateConfigurationType { get; set; }
        public Nullable<double> IntegratedEnergyFactor { get; set; }
        public Nullable<double> WaterRemovalCapcity { get; set; }
        public Nullable<System.DateTime> DateAvailable { get; set; }
        public string Market { get; set; }
        public string ModelIdentifier { get; set; }
        public Nullable<bool> Criteria { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual AppliancesType AppliancesType { get; set; }
    }
}
